#!/bin/sh
#
# @name IF750A SITL
# InspiredFlight 750 Auterion edition. Gazebo Only.
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults


param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.265
param set-default CA_ROTOR0_PY 0.265
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.265
param set-default CA_ROTOR1_PY -0.265
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.265
param set-default CA_ROTOR2_PY -0.265
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.265
param set-default CA_ROTOR3_PY 0.265
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

# EKF2: Multi GPS blending
param set-default SENS_GPS_MASK 7
# param set-default TRIG_INTERFACE 3
# param set-default TRIG_MODE 4
# param set-default MNT_MODE_IN 4
# param set-default MNT_MODE_OUT 2
# param set-default MNT_DO_STAB 2


